/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MetodoGauss;

import MetodoCrammer.*;
import static java.lang.Math.abs;
import java.text.DecimalFormat;

/**
 *
 * @author Kevinchatmajo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    double a1, a2, a3, b1, b2, b3, c1, c2, c3, d1, d2, d3;

    public void define() {
        a1 = Double.parseDouble(a1txt.getText());
        a2 = Double.parseDouble(a2txt.getText());
        a3 = Double.parseDouble(a3txt.getText());
        b1 = Double.parseDouble(b1txt.getText());
        b2 = Double.parseDouble(b2txt.getText());
        b3 = Double.parseDouble(b3txt.getText());
        c1 = Double.parseDouble(c1txt.getText());
        c2 = Double.parseDouble(c2txt.getText());
        c3 = Double.parseDouble(c3txt.getText());
        d1 = Double.parseDouble(d1txt.getText());
        d2 = Double.parseDouble(d2txt.getText());
        d3 = Double.parseDouble(d3txt.getText());
    }

    public Main() {
        initComponents();
    }

    public double deterS() {
        return (a1 * b2 * c3 + a2 * b3 * c1 + a3 * b1 * c2) - (a3 * b2 * c1 + a1 * b3 * c2 + a2 * b1 * c3);
    }

    public double deterX() {
        return (d1 * b2 * c3 + d2 * b3 * c1 + d3 * b1 * c2) - (d3 * b2 * c1 + d1 * b3 * c2 + d2 * b1 * c3);
    }

    public double deterY() {
        return (a1 * d2 * c3 + a2 * d3 * c1 + a3 * d1 * c2) - (a3 * d2 * c1 + a1 * d3 * c2 + a2 * d1 * c3);
    }

    public double deterZ() {
        return (a1 * b2 * d3 + a2 * b3 * d1 + a3 * b1 * d2) - (a3 * b2 * d1 + a1 * b3 * d2 + a2 * b1 * d3);
    }

    public double susEcu(int def, double var1, double var2) {
        if (def == 0) {
            return (d1 - (b1 * var1) - (c1 * var2)) / a1;
        } else if (def == 1) {
            return (d2 - (a2 * var1) - (c2 * var2)) / b2;
        } else if (def == 2) {
            return (d3 - (a3 * var1) - (b3 * var2)) / c3;
        } else {
            return 0;
        }
    }

    public double susEcuO(int def, double var1, double var2, double var3) {
        if (def == 0) {
            return (a1 * var1) + (b1 * var2) + (c1 * var3);
        } else if (def == 1) {
            return (a2 * var1) + (b2 * var2) + (c2 * var3);
        } else if (def == 2) {
            return (a3 * var1) + (b3 * var2) + (c3 * var3);
        } else {
            return 0;
        }
    }

    public double getError(double enew, double eant) {
        DecimalFormat errorp = new DecimalFormat("#.####");
        double error;
        error = abs((enew - eant) / enew) * 100;
        error = Double.valueOf(errorp.format(error));
        return error;
    }
    public double redondear(double cantidad){
        DecimalFormat errorp = new DecimalFormat("#.####");
        return Double.valueOf(errorp.format(cantidad));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1txt = new javax.swing.JTextField();
        a2txt = new javax.swing.JTextField();
        a3txt = new javax.swing.JTextField();
        b1txt = new javax.swing.JTextField();
        b2txt = new javax.swing.JTextField();
        b3txt = new javax.swing.JTextField();
        c1txt = new javax.swing.JTextField();
        c2txt = new javax.swing.JTextField();
        c3txt = new javax.swing.JTextField();
        d1txt = new javax.swing.JTextField();
        d2txt = new javax.swing.JTextField();
        d3txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(d3txt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(c1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(c2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(d1txt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(d2txt))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        define();
        double x = d1 / a1;
        double y = (d2 - a2 * x) / b2;
        double z = (d3 - a3 * x - b3 * y) / c3;
        double errord = 0.005;
        int i = 1;
        System.out.println("------------------------------");
        System.out.println("Interaccion : "+i);
        System.out.println("X : "+x);
        System.out.println("Y : "+y);
        System.out.println("Z : "+z);
        double resX = susEcuO(0, x, y, z);
        double resY = susEcuO(1, x, y, z);
        double resZ = susEcuO(2, x, y, z);
        double errort = (getError(d1, resX) + getError(d2, resY) + getError(d3, resZ)) / 3;
        System.out.println("Res X: "+resX);
        System.out.println("Res Y: "+resY);
        System.out.println("Res Z: "+resZ);
        System.out.println("Error 1° : " + getError(d1, resX) + "\n"
                + "Error 2° : " + getError(d2, resY) + "\n"
                + "Error 3° : " + getError(d3, resZ) + "\n"
                + "Error total : " + errort);
        while (errort > errord) {
            i++;
            System.out.println("------------------------------");
            System.out.println("Interaccion : "+i);
            x = susEcu(0, y, z);
            y = susEcu(1, x, z);
            z = susEcu(2, x, y);
            System.out.println("X: "+x);
            System.out.println("Y: "+y);
            System.out.println("Z: "+z);
            resX = susEcuO(0, x, y, z);
            resY = susEcuO(1, x, y, z);
            resZ = susEcuO(2, x, y, z);
            errort = (getError(d1, resX) + getError(d2, resY) + getError(d3, resZ)) / 3;
            System.out.println("Res X: "+resX);
            System.out.println("Res Y: "+resY);
            System.out.println("Res Z: "+resZ);
            System.out.println("Error 1° : " + getError(d1, resX) + "\n"
                    + "Error 2° : " + getError(d2, resY) + "\n"
                    + "Error 3° : " + getError(d3, resZ) + "\n"
                    + "Error total : " + errort);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1txt;
    private javax.swing.JTextField a2txt;
    private javax.swing.JTextField a3txt;
    private javax.swing.JTextField b1txt;
    private javax.swing.JTextField b2txt;
    private javax.swing.JTextField b3txt;
    private javax.swing.JTextField c1txt;
    private javax.swing.JTextField c2txt;
    private javax.swing.JTextField c3txt;
    private javax.swing.JTextField d1txt;
    private javax.swing.JTextField d2txt;
    private javax.swing.JTextField d3txt;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
