/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MetodoBiseccion;

import static java.lang.Math.abs;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevinchatmajo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        interv1 = new javax.swing.JTextField();
        interv2 = new javax.swing.JTextField();
        errordes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "x^6", "x^5", "x^4", "x^3", "x^2", "x", "#"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        interv1.setText("Intervalo 1");
        interv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interv1ActionPerformed(evt);
            }
        });

        interv2.setText("Intervalo 2");
        interv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interv2ActionPerformed(evt);
            }
        });

        errordes.setText("Error deseado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(interv1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interv2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errordes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errordes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(interv1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(interv2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(138, 138, 138))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Math.pow(1, 6) * (Integer.parseInt(tabla.getValueAt(0, 0)));
        int inter = Integer.parseInt(interv1.getText());
        int iner2 = Integer.parseInt(interv2.getText());
        double resul = 0;
        double inter1 = 0;
        double inter2 = 0;
        inter1 =( Math.pow(inter, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0)))) )+ 
                (Math.pow(inter, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1)))) )+
                (Math.pow(inter, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2))))) +
                (Math.pow(inter, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3)))) )+
                (Math.pow(inter, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4))))) +
                (inter * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5)))) )+
                (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6)))) ;
        System.out.println("inter 1: "+inter1);
        inter2 = (Math.pow(iner2, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0))))) + 
                (Math.pow(iner2, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1)))) )+
                (Math.pow(iner2, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2)))) )+
                (Math.pow(iner2, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3)))) )+
                (Math.pow(iner2, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4))))) +
                (iner2 * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5))))) +
                (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6)))) ;
        System.out.println("inter 2 "+inter2);
        System.out.println(inter1 * inter2);
        boolean banderin = false;
        double puntom = 0;
        double puntoant = 0;
        double error = 0;
        double errordeseado = Double.parseDouble(errordes.getText());
        int i = 0;
        int temp2 = 0;
        double resultado2 = 0;
        double resultado1 = 0;
        if(inter1 * inter2 < 0){
            inter1 = inter;
            inter2 = iner2;
            while(banderin == false){
                System.out.println("Interaccion "+(i+1)+" - - - - - - - - ");
                System.out.println("inter1 : "+inter1);
                System.out.println("inter2 : "+inter2);
                puntom = (inter1 + inter2)/2;
                DecimalFormat df = new DecimalFormat("#.######");
                puntom = Double.valueOf(df.format(puntom));  
                System.out.println("> > Punto medio : "+inter1+"+"+inter2+"/2 = "+puntom);
                System.out.println((Math.pow(puntom, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0))))
                        + Math.pow(puntom, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1))))
                        + Math.pow(puntom, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2))))
                        + Math.pow(puntom, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3))))
                        + Math.pow(puntom, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4))))
                        + puntom * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5))))
                        + (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6)))) ) ); 
                    System.out.println(inter2);
                    System.out.println("Punto medio : "+(Math.pow(puntom, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0))))
                        + Math.pow(puntom, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1))))
                        + Math.pow(puntom, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2))))
                        + Math.pow(puntom, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3))))
                        + Math.pow(puntom, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4))))
                        + puntom * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5))))
                        + (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6)))) ) * inter2);
                    resultado2 = (Math.pow(inter2, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0)))))
                        + (Math.pow(inter2, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1)))))
                        + (Math.pow(inter2, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2)))))
                        + (Math.pow(inter2, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3)))))
                        + (Math.pow(inter2, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4)))))
                        + (inter2 * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5)))))
                        + (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6))));
                    resultado1 = (Math.pow(inter1, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0)))))
                        + (Math.pow(inter1, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1)))))
                        + (Math.pow(inter1, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2)))))
                        + (Math.pow(inter1, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3)))))
                        + (Math.pow(inter1, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4)))))
                        + (inter1 * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5)))))
                        + (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6))));
                    System.out.println("Resultado 1 :"+resultado1);
                    System.out.println("Resultado 2 :"+resultado2);
                if(
                        (Math.pow(puntom, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0))))
                        + Math.pow(puntom, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1))))
                        + Math.pow(puntom, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2))))
                        + Math.pow(puntom, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3))))
                        + Math.pow(puntom, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4))))
                        + puntom * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5))))
                        + (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6)))) ) * resultado2
                        <= 0
                        &&
                        (Math.pow(puntom, 6) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0))))
                        + Math.pow(puntom, 5) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 1))))
                        + Math.pow(puntom, 4) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 2))))
                        + Math.pow(puntom, 3) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3))))
                        + Math.pow(puntom, 2) * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4))))
                        + puntom * (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 5))))
                        + (Integer.parseInt(String.valueOf(tabla.getValueAt(0, 6)))) ) * resultado1
                        > 0
                        ){
                    System.out.println("Es menor o igual a 0 por lo tanto iner1 cambia al puntom");
                    //System.out.println("inter1 antes :"+inter1);
                    //System.out.println("jajajadsjaspdjspaoj");
                    inter1 = puntom;
                    //System.out.println("inter1: "+inter1);
                }else{
                    System.out.println("Es mayor por lo tanto inter 2 cambia al puntom");
                    //System.out.println("inter2 antes :"+inter2);
                    inter2 = puntom;
                    //System.out.println("inter2 :"+inter2);
                }
                if (temp2 == 2) {
                    error = abs((puntom - puntoant) / puntom) * 100;
                    DecimalFormat errorp = new DecimalFormat("#.######");
                    error = Double.valueOf(errorp.format(error));
                    System.out.println("Error " + error + "%");
                    if (error <= errordeseado || i == 500) {
                        banderin = true;
                    }
                } else {
                    temp2++;
                }
                puntoant = puntom;
                i++;
            }
        }else if(inter1 * inter2 > 0){
            JOptionPane.showMessageDialog(this, "El valor fue positivo");
        }
        else if(inter1 * inter2 == 0){
            JOptionPane.showMessageDialog(this, "El valor fue 0");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void interv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interv1ActionPerformed

    private void interv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interv2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField errordes;
    private javax.swing.JTextField interv1;
    private javax.swing.JTextField interv2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
