/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FactorizacionLU;

import MetodoJordan.*;
import MetodoGauss.*;
import MetodoCrammer.*;
import static java.lang.Math.abs;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevinchatmajo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    double a1, a2, a3, b1, b2, b3, c1, c2, c3, d1, d2, d3;
    double ua1, ua2, ua3, ub1, ub2, ub3, uc1, uc2, uc3;
    double la1, la2, la3, lb1, lb2, lb3, lc1, lc2, lc3;
    
    public void define() {
        a1 = Double.parseDouble(a1txt.getText());
        a2 = Double.parseDouble(a2txt.getText());
        a3 = Double.parseDouble(a3txt.getText());
        b1 = Double.parseDouble(b1txt.getText());
        b2 = Double.parseDouble(b2txt.getText());
        b3 = Double.parseDouble(b3txt.getText());
        c1 = Double.parseDouble(c1txt.getText());
        c2 = Double.parseDouble(c2txt.getText());
        c3 = Double.parseDouble(c3txt.getText());
        d1 = Double.parseDouble(d1txt.getText());
        d2 = Double.parseDouble(d2txt.getText());
        d3 = Double.parseDouble(d3txt.getText());
    }

    public Main() {
        initComponents();
    }

    public void imp() {
        System.out.println(a1 + " " + b1 + " " + c1 + " | " + d1);
        System.out.println(a2 + " " + b2 + " " + c2 + " | " + d2);
        System.out.println(a3 + " " + b3 + " " + c3 + " | " + d3);
        System.out.println("-------------------------");
    }

    public double getError(double enew, double eant) {
        DecimalFormat errorp = new DecimalFormat("#.####");
        double error;
        error = abs((enew - eant) / enew) * 100;
        error = Double.valueOf(errorp.format(error));
        return error;
    }

    public double redondear(double cantidad) {
        DecimalFormat errorp = new DecimalFormat("#.####");
        return Double.valueOf(errorp.format(cantidad));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1txt = new javax.swing.JTextField();
        a2txt = new javax.swing.JTextField();
        a3txt = new javax.swing.JTextField();
        b1txt = new javax.swing.JTextField();
        b2txt = new javax.swing.JTextField();
        b3txt = new javax.swing.JTextField();
        c1txt = new javax.swing.JTextField();
        c2txt = new javax.swing.JTextField();
        c3txt = new javax.swing.JTextField();
        d1txt = new javax.swing.JTextField();
        d2txt = new javax.swing.JTextField();
        d3txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(d3txt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(c1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(c2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(d1txt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(d2txt))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        define();
        double ta, tb, tc, td;
        imp();
        try {
            if (a1 != 1) {
                ta = a1 / a1;
                tb = b1 / a1;
                tc = c1 / a1;
                td = d1 / a1;
                a1 = ta;
                b1 = tb;
                c1 = tc;
                d1 = td;
            }
            if (a2 != 0) {
                ta = (a1 * a2) * -1;
                tb = (b1 * a2) * -1;
                tc = (c1 * a2) * -1;
                td = (d1 * a2) * -1;
                a2 = a2 + ta;
                b2 = b2 + tb;
                c2 = c2 + tc;
                d2 = d2 + td;
            }
            if (a3 != 0) {
                ta = (a1 * a3) * -1;
                tb = (b1 * a3) * -1;
                tc = (c1 * a3) * -1;
                td = (d1 * a3) * -1;
                a3 = a3 + ta;
                b3 = b3 + tb;
                c3 = c3 + tc;
                d3 = d3 + td;
            }
            if (b2 != 1) {
                ta = a2 / b2;
                tb = b2 / b2;
                tc = c2 / b2;
                td = d2 / b2;
                a2 = ta;
                b2 = tb;
                c2 = tc;
                d2 = td;
            }
            imp();
            if (b1 != 0) {
                ta = (a2 * b1) * -1;
                tb = (b2 * b1) * -1;
                tc = (c2 * b1) * -1;
                td = (d2 * b1) * -1;
                a1 = a1 + ta;
                b1 = b1 + tb;
                c1 = c1 + tc;
                d1 = d1 + td;
            }
            if (b3 != 0) {
                ta = (a2 * b3) * -1;
                tb = (b2 * b3) * -1;
                tc = (c2 * b3) * -1;
                td = (d2 * b3) * -1;
                a3 = a3 + ta;
                b3 = b3 + tb;
                c3 = c3 + tc;
                d3 = d3 + td;
            }
            imp();
            if (c3 != 1) {
                ta = a3 / c3;
                tb = b3 / c3;
                tc = c3 / c3;
                td = d3 / c3;
                a3 = ta;
                b3 = tb;
                c3 = tc;
                d3 = td;
            }
            if (c2 != 0) {
                ta = (a3 * c2) * -1;
                tb = (b3 * c2) * -1;
                tc = (c3 * c2) * -1;
                td = (d3 * c2) * -1;
                a2 = a2 + ta;
                b2 = b2 + tb;
                c2 = c2 + tc;
                d2 = d2 + td;
            }
            if (c1 != 0) {
                ta = (a3 * c1) * -1;
                tb = (b3 * c1) * -1;
                tc = (c3 * c1) * -1;
                td = (d3 * c1) * -1;
                a1 = a1 + ta;
                b1 = b1 + tb;
                c1 = c1 + tc;
                d1 = d1 + td;
            }
            d1 = redondear(d1);
            d2 = redondear(d2);
            d3 = redondear(d3);
            imp();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifique sus ecuaciones");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1txt;
    private javax.swing.JTextField a2txt;
    private javax.swing.JTextField a3txt;
    private javax.swing.JTextField b1txt;
    private javax.swing.JTextField b2txt;
    private javax.swing.JTextField b3txt;
    private javax.swing.JTextField c1txt;
    private javax.swing.JTextField c2txt;
    private javax.swing.JTextField c3txt;
    private javax.swing.JTextField d1txt;
    private javax.swing.JTextField d2txt;
    private javax.swing.JTextField d3txt;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
